name: Build GTK# 2.12 assemblies
author: Fredrik Høisæther Rasch <fredrik.rasch@gmail.com>
description: Builds the .NET assemblies for GTK# 2.12 from the Mono Project source archive
inputs:
  version:
    required: true
    description: The three-part dot-separated version of GTK# to build
    default: '2.12.0'
  tarball-extension:
    required: true
    description: "The extension of the tarball archive to download including the leading period and tar part of the extension. E.g.: .tar.gz"
    default: .tar.bz2
  output-directory:
    required: true
    description: The output directory where the compiled assemblies will be placed
    default: ${{ github.workspace }}/lib
runs:
  using: composite
  steps:
    - id: docker-build-configure
      run: |
        echo "::group::docker build"
        docker build -t "${{ github.repository }}:${{ github.run_id }}" --build-arg GTKSHARPVERSION=${{ inputs.version }} --build-arg GKTSHARPTARBALLEXT=${{ inputs.tarball-extension }} - < "${{ github.action_path }}/Dockerfile"
        echo "::endgroup::"
      shell: bash
    - id: docker-run-make
      run: |
        echo "::group::make"
        docker run --rm -v "${{ inputs.output-directory }}:/usr/src/gtk-sharp-${{ inputs.version }}/lib" "${{ github.repository }}:${{ github.run_id }}" make
        echo "::endgroup::"
      shell: bash
