name: Build GTK# 2.12 assemblies
author: Fredrik Høisæther Rasch <fredrik.rasch@gmail.com>
description: Builds the .NET assemblies for GTK# 2.12 from the Mono Project source archive
inputs:
  version:
    required: true
    description: The three-part dot-separated version of GTK# to build
    default: '2.12.45'
  output-directory:
    required: true
    description: The output directory where the compiled assemblies will be placed
    default: ${{ github.workspace }}/artifacts
runs:
  using: composite
  steps:
    - id: docker-build-install-msi
      run: |
        echo "::group::docker build"
        docker build -t "${{ github.repository }}:${{ github.run_id }}" --build-arg GTKSHARPVERSION=${{ inputs.version }} - < "${{ github.action_path }}/windows.dockerfile"
        echo "::endgroup::"
      shell: bash
    - id: docker-create-container
      run: |
        echo "::group::docker build"
        echo "::set-output name=containerid::$(docker container create "${{ github.repository }}:${{ github.run_id }})"
        echo "::endgroup::"
      shell: bash
    - id: docker-cp-gtk-sharp
      run: |
        echo "::group::docker cp"
        docker cp "${{ steps.docker-create-container.outputs.containerid }}:C:\Program Files (x86)\GtkSharp\lib" "${{ inputs.output-directory }}"
        echo "::endgroup::"
      shell: bash
