name: Build GTK# 2.12
on:
  - push
  - pull_request
defaults:
  run:
    shell: pwsh
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Chekout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Mono GTK# Assemblies
        uses: ./.github/actions/compile-gtk-sharp
        with:
          version: "2.12.45"
          tarball-extension: .tar.gz
      - name: Upload compiled assemblies
        uses: actions/upload-artifact@v2
        with:
          name: gtk-sharp-lib
          path: |
            artifacts/lib/mono/gtk-sharp-2.0
            !artifacts/lib/mono/gtk-sharp-2.0/policy.*
