name: "Build GTK# 2.12"
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GTKSHARPVERSION: 2.12.45
      GKTSHARPTARBALLEXT: .tar.gz
    steps:
      - name: Chekout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Build Mono GTK# Assemblies"
        run: |
          docker build -t "${{ github.repository }}:${{ env.GTKSHARPVERSION }}" \
            --build-arg "GTKSHARPVERSION=${{ env.GTKSHARPVERSION }}" \
            --build-arg "GKTSHARPTARBALLEXT=${{ env.GKTSHARPTARBALLEXT }}" \
            - < Dockerfile
          docker run --rm -v "${{ github.workspace }}/artifacts:/opt" \
            "${{ github.repository }}:${{ env.GTKSHARPVERSION }}" \
            sh -c "make && make install && cp ./COPYING /opt/LICENSE"
      - name: Upload compiled assemblies
        uses: actions/upload-artifact@v2
        with:
          name: gtk-sharp-lib
          path: |
            artifacts/LICENSE
            artifacts/lib/mono/gtk-sharp-2.0
            !artifacts/lib/mono/gtk-sharp-2.0/policy.*
