name: "Build GTK# 2.12"
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GTKSHARPVERSION: 2.12.45
      GKTSHARPTARBALLEXT: .tar.gz
    steps:
      - name: Chekout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Build Mono GTK# Assemblies"
        run: |
          docker build -t "${{ github.repository }}:${{ env.GTKSHARPVERSION }}" \
            --build-arg "GTKSHARPVERSION=${{ env.GTKSHARPVERSION }}" \
            --build-arg "GKTSHARPTARBALLEXT=${{ env.GKTSHARPTARBALLEXT }}" \
            - < Dockerfile
          docker run --rm -v "${{ github.workspace }}/artifacts:/opt" \
            "${{ github.repository }}:${{ env.GTKSHARPVERSION }}" \
            sh -c "make && make install && cp ./COPYING /opt/LICENSE && cp -r ./doc/en /opt/monodoc"
          cp -r "${{ github.workspace }}/artifacts/monodoc" "${{ github.workspace }}/artifacts/monodoc-tmp"
        shell: bash
      - name: "Update Monodoc index"
        run: |
          [string]$MonodocIndexPath = Resolve-Path "${{ github.workspace }}/artifacts/monodoc-tmp/index.xml"
          [xml]$MonodocIndex = Get-Content -LiteralPath $MonodocIndexPath
          $MonodocTypeXml = $MonodocIndex.SelectSingleNode("/Overview/Types")
          $MonodocTypeXml.RemoveChild($MonodocTypeXml.SelectSingleNode("Namespace[@Name=`"GtkSharp.GnomeVfsSharp`"]")) | Out-Null
          $MonodocTypeXml.RemoveChild($MonodocTypeXml.SelectSingleNode("Namespace[@Name=`"Rsvg`"]")) | Out-Null
          $MonodocIndex.Save($MonodocIndexPath)
        shell: pwsh
      - name: "Export XML Documentation files"
        run: |
          mkdir -p ./artifacts/doc
          docker run --rm -v "${{ github.workspace }}/artifacts:/opt" \
            -w "/opt/doc" \
            "${{ github.repository }}:${{ env.GTKSHARPVERSION }}" \
            mdoc export-msxdoc /opt/monodoc-tmp
        shell: bash
      - name: Upload compiled assemblies
        uses: actions/upload-artifact@v2
        with:
          name: gtk-sharp-lib
          path: |
            artifacts/lib/mono/gtk-sharp-2.0
            !artifacts/lib/mono/gtk-sharp-2.0/policy.*
      - name: Upload XML Documentation files
        uses: actions/upload-artifact@v2
        with:
          name: gtk-sharp-lib
          path: artifacts/doc/*.xml
      - name: Upload LICENSE
        uses: actions/upload-artifact@v2
        with:
          name: gtk-sharp-lib
          path: artifacts/LICENSE
